### PR TITLE
Optional gcov

### PR DESCRIPTION
**Pull request by aminiussi**
It is currently difficult to use the module on environment that do not support gcov in the sens that including the file will just crash the build. 
The only alternative is to duplicate the environments tests in CodeCoverrage.cmake into the caller and only include if support is present.
This patch propose to make a faulty environment non fatal, but only provide the functionalities if it's present. 
The caller can then use the variable **COVERAGE_SUPPORTED**

```
if (CMAKE_BUILD_TYPE STREQUAL "Debug")
  include(CodeCoverage)
  if (COVERAGE_SUPPORTED)
    append_coverage_compiler_flags(--coverage)
    set(COVERAGE_EXCLUDES /opt /usr)
    setup_target_for_coverage(
      NAME cover
      EXECUTABLE ctest  
      DEPENDENCIES)
    message(INFO "run \"make cover\" to get coverage status.")
  endif()
endif()
```

### CODE REVIEW

**Comment by bilke** [comment]
Thanks for your contribution but I don't get the intention of this PR. Including which file crashes the build? If gcov somehow does not work in an environment it is out of scope of this CMake module to handle that.

**Comment by aminiussi** [comment]
Including CodeCoverage.cmake crashes the build due to the **FATAL_ERROR** used in the messages when a tool is not available.
Some of my build platforms have it, and some don't. Also, I don't alway build with gcc. 
I cannot crash my builds just because gcov is not available/working/supported in some specific situations, I need to detect those and work around them.

**Comment by aminiussi** [comment]
If that situation is out of scope, feel free to remove the PRs.

**Comment by bilke** [comment]
Ok now your intention is clear to me: Yes using the coverage stuff requires that its requirements are met (which I assume for a continuous integration machine for example). I would put `include(CodeCoverage) ...`  into an if-check, e.g.:

```cmake
option(USE_COVERAGE "..." OFF)
...
if(USE_COVERAGE)
  include(CodeCoverage)
  ...
endif()
```

I think this is a task from the calling side, so I will close this PR.

**Pull request closed without merging**
