### PR TITLE
include completely uncovered files in the coverage report

### PR DESCRIPTION
**Pull request by mahal-tu**
see "Recommended procedure when capturing data for a test case" in https://linux.die.net/man/1/lcov

### CODE REVIEW

**Comment by bilke** [comment]
Really nice addition, thank you!

**Comment by bilke** [comment]
@mahal-tu Can you please fix the indentation? You used tabs whereas spaces are used in the file. Thanks!

**Comment by mahal-tu** [comment]
sure!

**Comment by bigeasy** [comment]
My build now includes function declarations as source lines and those source lines are never executed. If I remove adding the `*.base` file to the `*.total` file I get what appears to be a better result. The first is as is. The second is with the base file removed.

screenshot 2018-03-18 15 32 16
screenshot 2018-03-18 15 33 28

**Comment by mahal-tu** [comment]
never seen this on ubuntu. Could you provide a working example for testing?

**Pull request merged**
